{% set version = "7.12.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-drake
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/drake_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/drake/drake_{{ version }}.tar.gz
  sha256: d5b30e00cb960d48cc7566e70ffff16920aceebb9b671440836d220d7c17f80a

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-base64url
    - r-digest >=0.6.21
    - r-igraph
    - r-rlang >=0.2.0
    - r-storr >=1.1.0
    - r-txtq >=0.1.3
    - r-vctrs >=0.2.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-base64url
    - r-digest >=0.6.21
    - r-igraph
    - r-rlang >=0.2.0
    - r-storr >=1.1.0
    - r-txtq >=0.1.3
    - r-vctrs >=0.2.0

test:
  commands:
    - $R -e "library('drake')"           # [not win]
    - "\"%R%\" -e \"library('drake')\""  # [win]

about:
  home: https://github.com/ropensci/drake
  license: GPL-3
  summary: A general-purpose computational engine for data analysis, drake rebuilds intermediate data objects when their dependencies change, and it skips work when the results are already up to date. Not every execution starts from scratch, there is native support for parallel and distributed computing, and completed projects
    have tangible evidence that they are reproducible. Extensive documentation, from beginner-friendly tutorials to practical examples and more, is available at the reference website <https://ropensci.github.io/drake/> and the online manual <https://ropenscilabs.github.io/drake-manual/>.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf
    - wlandau

# Package: drake
#Title: A Pipeline Toolkit for Reproducible Computation at Scale
#Version: 7.6.1
#Authors@R: c(
#  person(
#    given = c("William", "Michael"),
#    family = "Landau",
#    role = c("aut", "cre"),
#    email = "will.landau@gmail.com",
#    comment = c(ORCID = "0000-0003-1878-3253")
#  ),
#  person(
#    given = "Alex",
#    family = "Axthelm",
#    role = "ctb",
#    email = "aaxthelm@che.IN.gov"
#  ),
#  person(
#    given = "Jasper",
#    family = "Clarkberg",
#    role = "ctb",
#    email = "jasper@clarkberg.org"
#  ),
#  person(
#    given = "Kirill",
#    #family = "Müller",
#    role = "ctb",
#    email = "krlmlr+r@mailbox.org"
#  ),
#  person(
#    given = "Ben",
#    family = "Bond-Lamberty",
#    role = "ctb",
#    email = "bondlamberty@pnnl.gov",
#    comment = c(ORCID = "0000-0001-9525-4633")
#  ),
#  person(
#    given = "Tristan",
#    family = "Mahr",
#    role = "ctb",
#    email = "tristan.mahr@wisc.edu",
#    comment = c(ORCID = "0000-0002-8890-5116")
#  ),
#  person(
#    given = "Miles",
#    family = "McBain",
#    role = "ctb",
#    email = "miles.mcbain@gmail.com",
#    comment = c(ORCID = "0000-0003-2865-2548")
#  ),
#  person(
#    given = "Noam",
#    family = "Ross",
#    role = "ctb",
#    email = "noam.ross@gmail.com",
#    comment = c(ORCID = "0000-0002-2136-0000")
#  ),
#  person(
#    given = "Ben",
#    family = "Marwick",
#    role = "rev",
#    email = "bmarwick@uw.edu"
#  ),
#  person(
#    given = "Peter",
#    family = "Slaughter",
#    role = "rev",
#    email = "slaughter@nceas.ucsb.edu"
#  ),
#  person(
#    family = "Eli Lilly and Company",
#    role = "cph"
#  ))
#Description: A general-purpose computational engine for data
#  analysis, drake rebuilds intermediate data objects when their
#  dependencies change, and it skips work when the results are already up
#  to date.  Not every execution starts from scratch, there is native
#  support for parallel and distributed computing, and completed projects
#  have tangible evidence that they are reproducible.  Extensive
#  documentation, from beginner-friendly tutorials to practical examples
#  and more, is available at the reference website
#  <https://ropensci.github.io/drake/> and the online manual
#  <https://ropenscilabs.github.io/drake-manual/>.
#License: GPL-3
#URL: https://github.com/ropensci/drake
#BugReports: https://github.com/ropensci/drake/issues
#Depends:
#  R (>= 3.3.0)
#Imports:
#  base64url,
#  digest,
#  igraph,
#  methods,
#  rlang (>= 0.2.0),
#  storr (>= 1.1.0),
#  txtq (>= 0.1.3),
#  utils
#Suggests:
#  abind,
#  bindr,
#  callr,
#  cli (>= 1.1.0),
#  clustermq (>= 0.8.8),
#  crayon,
#  curl (>= 2.7),
#  datasets,
#  downloader,
#  fst,
#  future,
#  ggplot2,
#  ggraph,
#  grDevices,
#  keras,
#  knitr,
#  lubridate,
#  networkD3,
#  parallel,
#  prettycode,
#  Rcpp,
#  rmarkdown,
#  rstudioapi,
#  stats,
#  styler,
#  testthat (>= 2.1.0),
#  tibble,
#  tidyselect (>= 0.2.4),
#  txtplot,
#  usethis,
#  visNetwork,
#  webshot
#VignetteBuilder: 
#  knitr
#Encoding: UTF-8
#Language: en-US
#Roxygen: list(markdown = TRUE)
#RoxygenNote: 6.1.1
